// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT3p8fDDf0qX8BU6D-QqTgRN59dfXEdyw',
    appId: '1:563078917073:web:f9efe30b97be47e24a0ef0',
    messagingSenderId: '563078917073',
    projectId: 'fir-flutter-codelab-57d88',
    authDomain: 'fir-flutter-codelab-57d88.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-57d88.appspot.com',
    measurementId: 'G-PNCTV2TWBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7uxT0k2EZtBnmJRl6ZBb3KWBoVmjjxVY',
    appId: '1:563078917073:android:0264b7324264f2c54a0ef0',
    messagingSenderId: '563078917073',
    projectId: 'fir-flutter-codelab-57d88',
    storageBucket: 'fir-flutter-codelab-57d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9YYXyjpqeDLhlWcYP3O4i2YQuOfYytE',
    appId: '1:563078917073:ios:32007a66e3e120374a0ef0',
    messagingSenderId: '563078917073',
    projectId: 'fir-flutter-codelab-57d88',
    storageBucket: 'fir-flutter-codelab-57d88.appspot.com',
    iosBundleId: 'com.example.aplicacion2Jordychoez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9YYXyjpqeDLhlWcYP3O4i2YQuOfYytE',
    appId: '1:563078917073:ios:32007a66e3e120374a0ef0',
    messagingSenderId: '563078917073',
    projectId: 'fir-flutter-codelab-57d88',
    storageBucket: 'fir-flutter-codelab-57d88.appspot.com',
    iosBundleId: 'com.example.aplicacion2Jordychoez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT3p8fDDf0qX8BU6D-QqTgRN59dfXEdyw',
    appId: '1:563078917073:web:7f874322b0009e9b4a0ef0',
    messagingSenderId: '563078917073',
    projectId: 'fir-flutter-codelab-57d88',
    authDomain: 'fir-flutter-codelab-57d88.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-57d88.appspot.com',
    measurementId: 'G-B4NM0M3YXS',
  );
}
